// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWj3H1JwyZ1HapF5EKO0I8Tc0O4M8qQ2g',
    appId: '1:409626665608:web:027d787b19c2a13e63f53d',
    messagingSenderId: '409626665608',
    projectId: 'product-84441',
    authDomain: 'product-84441.firebaseapp.com',
    databaseURL: 'https://product-84441-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'product-84441.firebasestorage.app',
    measurementId: 'G-14CCZ5PWZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc7q00YmnLhqTCZd2qBDauG-xeebDMb-0',
    appId: '1:409626665608:android:4be3f96104f560b263f53d',
    messagingSenderId: '409626665608',
    projectId: 'product-84441',
    databaseURL: 'https://product-84441-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'product-84441.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKzyY1yWVoiDMsySSPBeJfvuz5I7neB18',
    appId: '1:409626665608:ios:22e0ac07859fcb0c63f53d',
    messagingSenderId: '409626665608',
    projectId: 'product-84441',
    databaseURL: 'https://product-84441-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'product-84441.firebasestorage.app',
    iosBundleId: 'com.example.batteryvision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKzyY1yWVoiDMsySSPBeJfvuz5I7neB18',
    appId: '1:409626665608:ios:22e0ac07859fcb0c63f53d',
    messagingSenderId: '409626665608',
    projectId: 'product-84441',
    databaseURL: 'https://product-84441-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'product-84441.firebasestorage.app',
    iosBundleId: 'com.example.batteryvision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWj3H1JwyZ1HapF5EKO0I8Tc0O4M8qQ2g',
    appId: '1:409626665608:web:dcf09adfdd6d26c163f53d',
    messagingSenderId: '409626665608',
    projectId: 'product-84441',
    authDomain: 'product-84441.firebaseapp.com',
    databaseURL: 'https://product-84441-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'product-84441.firebasestorage.app',
    measurementId: 'G-6YLFE6TFT5',
  );
}
